apiVersion: apps/v1
kind: Deployment
metadata:
  name: calender
  labels:
    exe: py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calender-app
  template:
    metadata:
      labels:
        app: calender-app
    spec:
      containers:
        - name: calender-container
          image: kukuhsatrio/calender-app:latest